name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{secrets.COMMIT_SECRET}}
      USER_NAME   : githubaction
      USER_EMAIL  : githubaction@fake.com
      PUBLISH_DIR : ./my-app
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      deployments: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install and Build
      run: cd my-app && npm i && npm run build
    - name: Handle Build Error
      if: ${{ failure() }}
      run: echo "Build failed" && exit 1
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        repo: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.COMMIT_SECRET }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: my-app/build # The folder the action should deploy.
        CLEAN: true # Automatically remove old files from the deployment branch