name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
        runs-on: ubuntu-latest
        timeout-minutes: 30
        permissions:
            contents: read
            deployments: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: cd my-app && npm i && npm run build
